version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - cyclop
    - dupl
    - errcheck
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - musttag
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - usestdlibvars
    - whitespace
    - wsl
  settings:
    asasalint:
      exclude:
        - \.Debugf
        - \.Infof
        - \.Warnf
        - \.Errorf
        - \.Fatalf
    depguard:
      rules:
        main:
          files:
            - "!**/*_a _file.go"
          allow:
            - $gostd
            - github.com/rezakhdemix
            - github.com/redis
          deny:
            - pkg: github.com/pkg/example
              desc: should be replaced by blah blah package
    dupl:
      threshold: 200
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 500
    gocyclo:
      min-complexity: 10
    govet:
      enable:
        - fieldalignment
        - nilfunc
        - nilness
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      confidence: 0.8
      severity: error
      enable-all-rules: true
      rules:
        - name: unused-parameter
          severity: warning
          disabled: false
        - name: unused-receiver
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 80
          severity: warning
          disabled: true
        - name: unchecked-type-assertion
          severity: warning
          disabled: true
        - name: add-constant
          arguments:
            - allowInts: 0,1,2,3,4
              allowStrs: '""'
              maxLitCount: "10"
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 10
          severity: warning
          disabled: true
        - name: max-public-structs
          arguments:
            - 10
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - asasalint
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
